<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-QJAOBPES" failures="1" tests="5" name="Test" time="27.115" errors="0" timestamp="2023-07-25T19:26:19 IST">
  <testcase classname="tests.TestFour" name="openApplication" time="6.329">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at tests.TestFour.openApplication(TestFour.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- openApplication -->
  <testcase classname="tests.TestThree" name="openApplication" time="10.004"/>
  <testcase classname="tests.TestOne" name="openApplication" time="10.528"/>
  <testcase classname="tests.LoginTest" name="loginTest" time="7.383"/>
  <testcase classname="tests.LoginTest" name="loginTest" time="11.774"/>
</testsuite> <!-- Test -->
